"""Shared tokenization for ranking and query generation."""

from __future__ import annotations

import re

_TOKEN_SPLIT = re.compile(r"[^a-z0-9]+")

STOPWORDS = frozenset(
    [
        "a",
        "about",
        "above",
        "after",
        "again",
        "all",
        "also",
        "among",
        "an",
        "and",
        "any",
        "are",
        "art",
        "as",
        "at",
        "based",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "could",
        "did",
        "do",
        "does",
        "doing",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "here",
        "how",
        "however",
        "i",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "just",
        "like",
        "more",
        "most",
        "much",
        "must",
        "new",
        "no",
        "nor",
        "not",
        "now",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "our",
        "out",
        "over",
        "own",
        "paper",
        "propose",
        "proposed",
        "proposes",
        "results",
        "same",
        "should",
        "show",
        "shown",
        "so",
        "some",
        "study",
        "such",
        "than",
        "that",
        "the",
        "their",
        "them",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "upon",
        "use",
        "used",
        "using",
        "very",
        "via",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "why",
        "will",
        "with",
        "within",
        "without",
        "work",
        "would",
        "you",
        "your",
    ]
)

MIN_TOKEN_LENGTH = 3


def tokenize(text: str) -> list[str]:
    """Lowercase alphanumeric tokens with stopwords and short tokens removed."""
    return [
        token
        for token in _TOKEN_SPLIT.split(text.lower())
        if len(token) >= MIN_TOKEN_LENGTH and token not in STOPWORDS
    ]
